In [115]:
import numpy as np
import pandas as pd
#from scipy import stats
#import seaborn
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
from sklearn.preprocessing import scale
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [127]:
data=pd.read_csv('orange_small_churn_data.txt')
data.shape

(40000, 230)

In [128]:
label=pd.read_csv('orange_small_churn_labels.txt',header=None)
label.shape

(40000, 1)

In [129]:
label.columns=['label']
X=data.iloc[:28000,:]
y=label.iloc[:28000,:]
X_holdout=data.iloc[-12000:,:]
y_holdout=label.iloc[-12000:,:]
print X.shape,X_holdout.shape
print y.shape,y_holdout.shape

(28000, 230) (12000, 230)
(28000, 1) (12000, 1)


In [130]:
#Отбросим колонки где данных вообще нет
zero=list()
s=X.describe()
for var in s.columns:
    if s[var]['count']==0:zero.append(var)
print zero
print 'Колонки ,которые мы отбросили', len(zero)
real_columns=X.columns.drop(zero)
X=X[real_columns]

['Var8', 'Var15', 'Var20', 'Var31', 'Var32', 'Var39', 'Var42', 'Var48', 'Var52', 'Var55', 'Var79', 'Var141', 'Var167', 'Var169', 'Var175', 'Var185', 'Var209', 'Var230']
Колонки ,которые мы отбросили 18


In [131]:
X.shape

(28000, 212)

In [132]:
#Из 230 колонок выбросли уже 18 где нет данных(из них 16 вещ. и 2 кат.).190(последняя вещ.)-16=174
num_data=X.iloc[:,:174]
cat_data=X.iloc[:,174:]
print num_data.shape
print y.shape


(28000, 174)
(28000, 1)


In [133]:
#Разница в значениях вещ.признаков достигает нескольких порядков!! -применим масштабирование
#Заполним средним по столбцу значения NaN иначе scale не сработает
num_data_mean=num_data.fillna(num_data.describe().loc['mean'])
#num_scaled=pd.DataFrame(scale(num_data_mean),columns=num_data.columns)

In [134]:
num_data_mean

Var1      Var2        Var3      Var4           Var5         Var6  \
0      10.129199  0.007194  499.301153  0.144165  261114.121795  3052.000000   
1      10.129199  0.007194  499.301153  0.144165  261114.121795  1813.000000   
2      10.129199  0.007194  499.301153  0.144165  261114.121795  1953.000000   
3      10.129199  0.007194  499.301153  0.144165  261114.121795  1533.000000   
4      10.129199  0.007194  499.301153  0.144165  261114.121795   686.000000   
5       0.000000  0.007194  499.301153  0.144165  261114.121795  1302.354079   
6      10.129199  0.007194  499.301153  0.144165  261114.121795   889.000000   
7      10.129199  0.007194  499.301153  0.144165  261114.121795   161.000000   
8      10.129199  0.007194  499.301153  0.144165  261114.121795   420.000000   
9      10.129199  0.007194  499.301153  0.144165  261114.121795  1155.000000   
10     10.129199  0.007194  499.301153  0.144165  261114.121795   147.000000   
11     10.129199  0.007194  499.301153  0.144165  261114.121795   539.000000   
12     10.129199  0.007194  499.301153  0.144165  261114.121795   462.000000   
13     10.129199  0.007194  499.301153  0.144165  261114.121795  1687.000000   
14     10.129199  0.007194  499.301153  0.144165  261114.121795   819.000000   
15     10.129199  0.007194  499.301153  0.144165  261114.121795   637.000000   
16     10.129199  0.007194  499.301153  0.144165  261114.121795   231.000000   
17     10.129199  0.007194  499.301153  0.000000  261114.121795  1302.354079   
18     10.129199  0.007194  499.301153  0.144165  261114.121795   574.000000   
19     10.129199  0.007194  499.301153  0.144165       0.000000  1302.354079   
20     10.129199  0.007194  499.301153  0.144165  261114.121795     0.000000   
21     10.129199  0.007194  499.301153  0.144165  261114.121795   301.000000   
22     10.129199  0.007194  499.301153  0.144165  261114.121795  3941.000000   
23     10.129199  0.007194  499.301153  0.000000  261114.121795  1302.354079   
24     10.129199  0.007194  499.301153  0.144165  261114.121795   147.000000   
25     10.129199  0.007194  499.301153  0.144165  261114.121795  3262.000000   
26     10.129199  0.007194  499.301153  0.144165  261114.121795   798.000000   
27     10.129199  0.007194  499.301153  0.144165  261114.121795  1323.000000   
28     10.129199  0.007194  499.301153  0.144165  261114.121795   938.000000   
29     10.129199  0.007194  499.301153  0.144165  261114.121795   252.000000   
...          ...       ...         ...       ...            ...          ...   
27970  10.129199  0.007194  499.301153  0.144165  261114.121795  2863.000000   
27971  10.129199  0.007194  499.301153  0.144165  261114.121795   350.000000   
27972  10.129199  0.007194  499.301153  0.144165  261114.121795   490.000000   
27973  10.129199  0.007194  499.301153  0.144165  261114.121795   623.000000   
27974  10.129199  0.007194  499.301153  0.144165  261114.121795  2107.000000   
27975  10.129199  0.007194  499.301153  0.144165  261114.121795  1043.000000   
27976  10.129199  0.007194  499.301153  0.000000  261114.121795  1302.354079   
27977  10.129199  0.007194  499.301153  0.144165  261114.121795  2779.000000   
27978  10.129199  0.007194  499.301153  0.144165  261114.121795  1561.000000   
27979  10.129199  0.007194  499.301153  0.144165  261114.121795  1890.000000   
27980  10.129199  0.007194  499.301153  0.144165  261114.121795   245.000000   
27981  10.129199  0.007194  499.301153  0.144165  261114.121795   896.000000   
27982  10.129199  0.007194  499.301153  0.144165  261114.121795  1113.000000   
27983  10.129199  0.007194  499.301153  0.144165  261114.121795  1974.000000   
27984  10.129199  0.007194  499.301153  0.144165  261114.121795     0.000000   
27985  10.129199  0.007194  499.301153  0.144165  261114.121795   427.000000   
27986  10.129199  0.007194  499.301153  0.144165  261114.121795   301.000000   
27987  10.129199  0.007194  499.301153  0.144165  261114.121795  1246.000000   
27988  10.12

In [38]:
#Поделим выборку на классы, чтобы посчитать корреляции для вещ. и категориального признаков
num_scaled_data=num_scaled.join(y)
num_scaled_data1=num_scaled_data[num_scaled_data.label==1.0]
num_scaled_data0=num_scaled_data[num_scaled_data.label==-1.0]
print num_scaled_data1.shape
print num_scaled_data0.shape
#Классы несбалансированы!

(2101, 175)
(25899, 175)


In [39]:
#Считаем корреляции для вещ.
corr=list()
for var in num_scaled_data.columns:
    c=num_scaled_data1[var].mean()-num_scaled_data0[var].mean()
    corr.append(c)
#Записываем в последнюю строку
num_scaled_data.loc[len(num_scaled_data)]=corr
#Выделяем эту строку с названиями переменных
res=num_scaled_data.drop('label',1).iloc[28000:,:].T
print res

           28000
Var1    0.007746
Var2   -0.003595
Var3   -0.002740
Var4    0.008830
Var5   -0.006784
Var6   -0.078762
Var7   -0.260574
Var9    0.000525
Var10   0.024959
Var11  -0.010731
Var12   0.018655
Var13  -0.165978
Var14  -0.019490
Var16  -0.009107
Var17  -0.006464
Var18  -0.003081
Var19   0.031538
Var21  -0.029223
Var22  -0.029546
Var23  -0.009849
Var24  -0.033564
Var25  -0.032096
Var26  -0.001621
Var27  -0.014405
Var28   0.050863
Var29  -0.006015
Var30  -0.002595
Var33  -0.020850
Var34  -0.013054
Var35   0.038769
...          ...
Var157 -0.008624
Var158 -0.003819
Var159  0.002397
Var160 -0.050888
Var161  0.019954
Var162  0.007266
Var163  0.008028
Var164 -0.008257
Var165 -0.003755
Var166 -0.013313
Var168 -0.082873
Var170  0.003971
Var171 -0.005765
Var172 -0.013412
Var173  0.043163
Var174  0.001775
Var176 -0.015053
Var177  0.031914
Var178 -0.017099
Var179  0.005075
Var180  0.010253
Var181 -0.002389
Var182 -0.007182
Var183  0.009039
Var184  0.005241
Var186  0.004563
Var187  0.0028

In [40]:
#Выбираем 20 наиболее коррелирущих числовых переменных
top20=(np.absolute(res)).nlargest(20,28000).T
print top20

         Var189     Var73      Var7    Var113    Var144     Var13     Var65  \
28000  0.316838  0.274598  0.260574  0.210127  0.193529  0.165978  0.162428   

        Var126     Var81     Var74     Var72    Var140    Var168      Var6  \
28000  0.15285  0.149044  0.127481  0.117881  0.101394  0.082873  0.078762   

         Var143    Var160     Var28    Var131    Var125    Var139  
28000  0.064594  0.050888  0.050863  0.050493  0.050304  0.046215  


In [41]:
#Удалим 65 - сильно коррелирует с 7 и 72
corr = num_data[top20.columns].corr()
print corr[(corr > 0.64) * (corr < 1.0)].dropna(axis=1,how="all")

            Var7     Var65     Var72
Var189       NaN       NaN       NaN
Var73        NaN       NaN       NaN
Var7         NaN  0.641425       NaN
Var113       NaN       NaN       NaN
Var144       NaN       NaN       NaN
Var13        NaN       NaN       NaN
Var65   0.641425       NaN  0.668722
Var126       NaN       NaN       NaN
Var81        NaN       NaN       NaN
Var74        NaN       NaN       NaN
Var72        NaN  0.668722       NaN
Var140       NaN       NaN       NaN
Var168       NaN       NaN       NaN
Var6         NaN       NaN       NaN
Var143       NaN       NaN       NaN
Var160       NaN       NaN       NaN
Var28        NaN       NaN       NaN
Var131       NaN       NaN       NaN
Var125       NaN       NaN       NaN
Var139       NaN       NaN       NaN


In [42]:
top19=top20.columns.drop('Var65')#удалили 65

In [43]:
num=num_scaled_data[top19].iloc[:28000,:]# выборка с вещественными признаками
num

Var189     Var73      Var7    Var113    Var144     Var13  \
0      0.000000 -0.617318  0.000000 -1.389937 -0.244123  0.000000   
1      0.103905  1.166375  0.037845  0.745863  0.567744 -0.235159   
2      0.000000  1.887443  0.037845  0.033987  1.379611 -0.307607   
3      0.000000 -0.693220  0.037845  0.694093 -1.055989 -0.478707   
4      0.000000 -0.655269  0.037845  0.384629 -0.244123 -0.480249   
5     -1.709709 -1.186581  0.000000 -4.371550  0.000000  0.000000   
6      0.000000 -0.769121 -1.140776  0.362670 -0.244123 -0.480249   
7     -0.322828 -0.920925 -1.140776  0.661401 -1.055989 -0.480249   
8      0.000000 -0.845023 -1.140776  0.146907 -1.055989 -0.480249   
9      0.000000 -0.731170 -1.140776  0.136908 -1.055989 -0.480249   
10     0.000000 -0.958876 -1.140776  0.940496 -1.055989 -0.480249   
11    -0.536194 -0.731170 -1.140776  0.371249  0.567744 -0.480249   
12     0.000000  1.963345  1.216466 -1.020183  3.003344  1.764093   
13    -1.282976 -0.731170 -1.140776  0.290775 -1.055989 -0.480249   
14     0.423954  0.369406  0.037845  0.210985 -1.055989  0.452325   
15     0.000000 -0.731170 -1.140776  0.390354  0.567744 -0.480249   
16     0.000000  0.786866  0.037845 -2.162498 -1.055989 -0.282944   
17     2.450934 -1.110680  0.000000 -2.156058  0.000000  0.000000   
18    -0.856244 -0.161907  0.037845  0.025639  0.567744 -0.469458   
19     0.000000 -1.072729  0.000000 -0.222234  0.000000  0.000000   
20     0.000000 -0.882974 -1.140776  0.197535 -0.244123 -0.480249   
21    -1.603025  0.938670  0.037845  1.148228  1.379611 -0.457127   
22     0.000000 -0.351661  0.037845  0.346080  1.379611  1.594534   
23     0.000000 -1.110680  0.000000 -1.933416  0.000000  0.000000   
24    -0.429511 -0.920925 -1.140776  0.256906 -0.244123 -0.480249   
25    -0.216145 -0.313710  1.216466 -1.788587 -1.055989 -0.358474   
26     0.000000  0.559161  0.037845  0.292027 -0.244123  0.882387   
27    -0.749560 -0.161907  0.037845  0.397987 -0.244123 -0.173501   
28     0.317271 -0.579367  0.037845 -0.902570 -1.055989 -0.475624   
29     0.000000 -0.958876 -1.140776  0.569845 -1.055989 -0.480249   
...         ...       ...       ...       ...       ...       ...   
27970  0.000000 -0.275759  0.037845  0.734900 -0.244123 -0.480249   
27971  1.170736 -0.237809  0.037845  0.199726 -1.055989 -0.417049   
27972  0.000000 -0.123956  0.037845  0.341227  0.567744 -0.224369   
27973 -1.176293 -0.048054  0.037845  0.242462 -0.244123 -0.127258   
27974  3.197715 -0.237809  0.037845  0.012244 -0.244123  0.329009   
27975 -0.642877 -0.048054  0.037845  0.328309 -0.244123  0.712829   
27976  0.000000 -1.110680  0.000000 -1.456991  0.000000  0.000000   
27977  0.000000  0.748915  0.037845  0.339115  0.567744  1.283163   
27978  0.103905 -0.199858 -1.140776  0.247831  0.567744 -0.352309   
27979  2.024201 -0.313710 -1.140776  0.417088 -1.055989 -0.474083   
27980 -0.109462 -0.845023 -1.140776  0.353004 -0.244123 -0.480249   
27981 -0.856244  0.862768  0.037845  0.216607 -0.244123 -0.417049   
27982  0.000000  0.976621  0.037845  0.198372  2.191478 -0.386220   
27983  0.000000  0.293504  2.395087  0.408178 -0.244123  2.699749   
27984  0.000000 -1.034778 -1.140776  0.131887 -1.055989 -0.480249   
27985  0.000000 -0.731170 -1.140776  1.588080  0.567744 -0.480249   
27986  0.000000 -0.920925 -1.140776  0.538466 -0.244123 -0.480249   
27987 -0.109462  1.621786  0.037845  0.144178  1.379611 -0.417049   
27988  0.000000  1.166375  0.037845  0.430761  3.003344  0.438452   
27989  0.423954 -0.048054  0.037845  0.660333  0.567744  0.221108   
27990  0.000000  0.369406  0.037845  0.624609  0.567744 -0.387762   
27991  0.000000 -0.958876 -1.140776 -0.221726 -1.055989 -0.480249   
27992  0.000000 -0.313710  0.037845  0.217748 -1.055989 -0.417049   
27993 -2.563174 -0.541416  0.037845  0.032494 -1.055989 -0.472541   
27994  0.000000  1.166375  0.037845  0.384905  3.003344 -0.158087   
27995 -1.389659 -0.617318  0.037845  0.580330 -0.244123 -0.471000   
27996  

In [135]:
cat_data=cat_data.fillna('NA')
#cat_data=cat_data.join(y)

In [45]:
#Отбираем категориальные по Крамеру с достижением значимости <0.05
k=0
new=list()
from scipy import stats
from math import sqrt
for var in cat_data.columns.drop(label):
    subtable=pd.crosstab(cat_data[var], cat_data.label)
    ch2,p,dof,e=stats.chi2_contingency(subtable,correction=False)
    cramer=sqrt(ch2/(sum(subtable.sum())-1))
    if p<0.05 and cramer>0.07 and len(cat_data[var].value_counts())<100 : 
        k+=1
        print 'Var ,p,cramer',var,p,cramer
        print len(cat_data[var].value_counts())
        new.append(var)
print k
print new
cat=cat_data[new]
print cat

Var ,p,cramer Var193 3.55647398956e-13 0.0739638072254
48
Var ,p,cramer Var205 6.86475793867e-32 0.0727219318482
4
Var ,p,cramer Var206 1.79179794029e-31 0.0848445723764
22
Var ,p,cramer Var212 1.69160282443e-21 0.0951564396571
75
Var ,p,cramer Var218 1.42205763577e-67 0.104855885368
3
Var ,p,cramer Var228 2.03000048467e-22 0.0785866281257
30
6
['Var193', 'Var205', 'Var206', 'Var212', 'Var218', 'Var228']
                       Var193   Var205   Var206         Var212 Var218  \
0                     AERks4l     09_Q     IYzP     JBfYVit4g8   cJvF   
1                     2Knk1KF     VpdQ     haYg  XfqtO3UdzaXh_   cJvF   
2            LrdZy8QqgUfkVShG     VpdQ     hAFG  4kVnq_T26xq1p   UYBR   
3                        RO12     VpdQ     IYzP        NhsEn4L   cJvF   
4                        RO12  sJzTlal     zm5i        NhsEn4L   cJvF   
5                        RO12     09_Q       NA           CrNX   cJvF   
6                        RO12  sJzTlal     zm5i        NhsEn4L   UYBR   
7       

In [136]:
from sklearn.feature_extraction import DictVectorizer
encoder = DictVectorizer(sparse = False)
cat_code = encoder.fit_transform(cat.T.to_dict().values())
print (cat_code)

[[ 0.  0.  0. ...,  0.  0.  1.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [137]:
cat_code.shape

(28000L, 182L)

In [138]:
X_select=np.hstack( (num_data_mean,cat_code))
X_select.shape

(28000L, 356L)

In [139]:
(X_train,  X_test,  y_train, y_test) = train_test_split(X_select, np.array(y), test_size=0.3, random_state=0)
print (X_train.shape)
print (X_test.shape)

(19600L, 356L)
(8400L, 356L)


In [118]:
X_train

array([[ 0.53063717,  0.14170059,  2.39508694, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42951101, -0.69321957,  0.03784498, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.74400343,  0.407357  ,  2.39508694, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [-0.21614475, -0.27575949, -1.140776  , ...,  0.        ,
         0.        ,  0.        ],
       [-0.21614475,  0.93866983,  2.39508694, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  3.02597023,  0.03784498, ...,  0.        ,
         0.        ,  0.        ]])

In [140]:
y_train=y_train.reshape(19600,)
y_test=y_test.reshape(8400,)
y_test

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [141]:
def metr(a,b):
    print metrics.classification_report(a,b)
    print 'accuracy', metrics.accuracy_score(a,b)
    print 'roc-auc',metrics.roc_auc_score(a,b)
    print 'PR AUC',metrics.average_precision_score(a,b)

In [146]:
clf=RidgeClassifier(class_weight='balanced',random_state=1)
cv=StratifiedKFold(n_splits=3)
clf.fit(X_train,y_train)
RC=cross_val_score(clf,X_train,y_train)
print RC
pred=clf.predict(X_test)
metr(y_test, pred)
clf.coef_

[ 0.60896847  0.60615338  0.61656207]
             precision    recall  f1-score   support

         -1       0.95      0.60      0.73      7757
          1       0.11      0.60      0.19       643

avg / total       0.88      0.60      0.69      8400

accuracy 0.599880952381
roc-auc 0.602217612708
PR AUC 0.373242394986


array([[  4.48118776e-03,   6.49585660e-02,  -2.27442759e-06,
          5.59236737e-02,   1.15376072e-08,  -1.67778832e-06,
         -4.95647822e-03,   2.23426681e-02,   9.02266198e-08,
         -2.54028355e-02,   1.71635657e-02,  -1.30434488e-06,
         -2.76342206e-02,  -1.16052008e-03,  -1.76497713e-02,
          1.06294366e-02,   8.09382387e-02,   1.15234944e-03,
         -1.16500474e-03,   5.22594621e-03,  -1.13611172e-03,
          2.33479395e-04,   2.01792613e-01,  -9.22080954e-02,
          1.33021858e-06,   1.19442798e-02,  -3.86084737e-02,
         -5.61184159e-07,  -8.79875555e-03,  -2.24674979e-02,
          2.16778892e-07,  -4.02779359e-08,   5.82815635e-09,
         -4.63362567e-04,   2.52600770e-03,  -2.22745809e-02,
         -2.34701922e-02,  -2.54317338e-05,  -6.46911297e-03,
          4.13690929e-03,  -7.51270502e-02,   1.70396950e-04,
         -4.03005078e-07,   2.17237114e-07,   2.98831699e-02,
          8.33946403e-08,  -4.06390127e-03,  -2.33459613e-08,
        

In [143]:
clf=RandomForestClassifier(class_weight='balanced',random_state=1)
cv=StratifiedKFold(n_splits=3)
clf.fit(X_train,y_train)
RC=cross_val_score(clf,X_train,y_train)
print RC
pred=clf.predict(X_test)
metr(y_test, pred)

[ 0.92470156  0.92530231  0.92514924]
             precision    recall  f1-score   support

         -1       0.92      1.00      0.96      7757
          1       0.11      0.00      0.00       643

avg / total       0.86      0.92      0.89      8400

accuracy 0.922619047619
roc-auc 0.500261941705
PR AUC 0.0945474462465


In [144]:
clf=GradientBoostingClassifier(random_state=1)
cv=StratifiedKFold(n_splits=3)
clf.fit(X_train,y_train)
RC=cross_val_score(clf,X_train,y_train)
print RC
pred=clf.predict(X_test)
metr(y_test, pred)

[ 0.92500765  0.92407776  0.9248431 ]
             precision    recall  f1-score   support

         -1       0.92      1.00      0.96      7757
          1       0.60      0.01      0.03       643

avg / total       0.90      0.92      0.89      8400

accuracy 0.92380952381
roc-auc 0.506611697336
PR AUC 0.344736540028


In [145]:
clf=SGDClassifier(random_state=1,class_weight='balanced')
cv=StratifiedKFold(n_splits=3)
clf.fit(X_train,y_train)
RC=cross_val_score(clf,X_train,y_train)
print RC
pred=clf.predict(X_test)
metr(y_test, pred)

[ 0.32736455  0.70978111  0.07684066]
             precision    recall  f1-score   support

         -1       0.92      0.64      0.75      7757
          1       0.07      0.31      0.11       643

avg / total       0.85      0.62      0.71      8400

accuracy 0.615119047619
roc-auc 0.475683429265
PR AUC 0.215334859007


In [ ]:
np.random.seed(0)
indices_to_add = np.random.randint(1884,size=(np.sum(y_train==0)-np.sum(y_train==1)))
#print X_train_scaled_cat.shape
X_train_to_add =X_train_scaled_cat[y_train.as_matrix() == 1,:][indices_to_add,:]
#print X_train_to_add.shape
#print y_train.shape
X_add=np.vstack( (X_train_scaled_cat,X_train_to_add) )
#print X_add.shape
ones= np.ones((432))
y_add=np.hstack((y_train, ones))
#print y_add.shape